name: Update blog

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Make HTTP Request
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $API_KEY" \
            -H "Content-Type: application/json" \
            https://blog.tomrochette.com/refresh-pages.php
